---
title: No me salen las tablas
author: Pedro
date: '2018-01-16'
slug: no-me-salen-las-tablas
categories: []
tags:
  - pruebas
---



```{r chunk_setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, eval = TRUE )
```

```{r options_setup, echo = FALSE}
options(scipen = 999) #- para quitar la notacion científica
```
 
```{r cargar_pkgs, echo = FALSE}
library("personal.pjp")
library(mypkgDataforblog) #- personal pkg
library(stringr)
library(tidyverse)
library(kableExtra)
```


Pues eso, que quiero ver como salen las tablas:


```{r}
df <- cod_INE_muni_pjp
df <- df %>% mutate(NOMBRE_tmp = NombreMuni) %>% 
  separate(NOMBRE_tmp, into = c("name_1", "name_2"), sep = "/")  %>% 
  mutate(yes_2_names = if_else(is.na(name_2), 0.0, 1.0)) %>% 
  select(INECodMuni, NombreMuni, yes_2_names, name_1, name_2, NombreCCAA, everything())
aa <- df %>% group_by(NombreCCAA) %>% 
  summarise(Municipios = n(), dos_nombres = sum(yes_2_names), percent = dos_nombres/Municipios) %>% 
  filter(dos_nombres != 0) %>% 
  arrange(desc(percent))
```



```{r}
library(knitr)
aa %>% kable(format = "markdown", caption = "Tabla 1", digits = 2)
```


```{r}
library(knitr)
aa %>% kable(format = "markdown", results = "asis")
```




```{r}
aa %>% kable(format = "pandoc")
```


```{r}
library(knitr)
aa %>% kable(format = "pandoc", results = "asis")
```


```{r}
library(knitr)
aa %>% kable(format = "pandoc", results = "markup")
```



```{r}
aa %>% kable(format = "html", results = "asis")
```



```{r}
aa %>% kable(format = "html", results = "markup")
```




```{r}
library(kableExtra)
aa %>% kable("html", results = "asis", digits = 2, caption = "Cuadro 1: Municipios españoles con dos nombres oficiales (por CC.AA.)") %>% 
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```




```{r}
kable(aa, "html") %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
```



```{r}
library("pander")
pander(aa, style = "rmarkdown")

```

```{r}
library("pander")
pander(aa, style = "grid")

```


```{r}
library(stargazer)
stargazer(aa, type = "html") 
```




```{r}
library(formattable)
formattable(aa)
```


Ni las formulas

$$y_{1}$$



